-- 02_erp_users  模拟 ERP 的操作员账号
--
-- ⚠️ 这个文件**故意是空的**，不要往里写 INSERT。
--
-- 模拟 ERP 的操作员账号由应用**启动时自建**，见 `mock/erp/app/seed.py`：
-- 当 erp_users 表为空时，读 .env 的 MOCK_ERP_USERNAME / MOCK_ERP_PASSWORD
-- 建出那唯一一个账号。不放在这里的理由是**口令哈希必须是运行时算的** ——
-- bcrypt 每次哈希都带新盐（同样的口令两次结果不同，这是对的），
-- 写死在 SQL 里等于把口令固化进版本库，而且还得手工算哈希、改口令时再算一遍。
--
-- 主平台的管理员账号同理，也在 Python 里种（scripts/seed_admin.py）。
-- 判断「该不该种」的口径一致：**表里一条都没有才种**，所以重复启动不会重复插入、
-- 也不会覆盖你手工改过密码的账号。
--
-- 所以本文件留在仓库里只是占位 + 说明：
--   - 想在干净环境里跑起模拟 ERP，执行 scripts/init_db.sh（或 init_test_db.sh）
--     建表，再启动一次服务，账号和库存就都有了；
--   - 测试环境不要指望它 —— mock/erp/tests/conftest.py 自己造操作员，
--     走的是真实的 POST /login，连 token 写没写进 session 都一并验了。
